### ISSUE TITLE
Choose best development environment

### ISSUE THREAD

**Issue by ateucher** [bcgov/designatedlands#64]
The dependency stack for this is relatively complex, possibly using conda would be easier? Or perhaps use Docker?

**Comment by smnorris** [comment]
I definitely find conda useful for windows installation of the GDAL related Python packages.

For postgres, my personal preference is to keep db installation and setup separate from Python tools like this (I use the same local db installation for many jobs) but I think everyone should already have postgres installed! 🙃  But yes, evaluating installation of postgres/postgis conda does seem worth a shot. Providing a Docker image with everything installed is likely straightforward, but I wonder if installing and using Docker is any simpler than installing and configuring postgres.

I think lostgis was the only other tricky dependency - installation of that isn't really required. We can just package the 3 or 4 sql functions with designatedlands rather than messing about with pgxn.
